spring:
  data:
    mongodb:
      uri: mongodb://10.10.8.238:27017/business
server:
  port: 9000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    auth-service:
      path: /uaa/**
      serviceId: auth-service
      stringPrefix: false
      sersitiveHeaders:
    sports-service:
      path: /**/sports/**
      serviceId: sports
      stringPrefix: false
      sersitiveHeaders:
    user-service:
      path: /**/user/**
      serviceId: user-service
      stringPrefix: false
      sersitiveHeaders:
    club-service:
      path: /**/club/**
      serviceId: club-service
      stringPrefix: false
      sersitiveHeaders:

