#server:
#  port: 23111

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/business
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: 10.10.8.238:2181
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    metadataMap:
      cluster: SPORTS-SERVICE
 client:
    serviceUrl:
      defaultZone: http://10.10.8.238:8761/eureka/