server:
  port: 23112
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    metadataMap:
      cluster: USER-SERVICE

#      uri: mongodb://127.0.0.1:27017/business
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.10.8.238:9092
          zkNodes: 10.10.8.238:2181
          offsetUpdateTimeWindow: 10000
          #offsetUpdateCount: 0
          requiredAcks: 1
          minPartitionCount: 1
          replicationFactor: 1
        bindings:
          input:
            consumer:
              autoCommitOffset: true
              startOffset: earliest
              headerMode: raw
          output:
            producer:
              bufferSize: 16384
              sync: true
              batchTimeout: 0

version: test_v_bus/refresh